#!/bin/sh
# Linux Standard Base comments
### BEGIN INIT INFO
# Provides:          CrashPlanEngine
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CrashPlan Engine
# Description:       CrashPlan backup service engine
### END INIT INFO

#############################################################
# Init script for CrashPlanEngine
#############################################################

# Defaults
SCRIPTNAME=/opt/crashplan/bin/CrashPlanEngine

case "$1" in
start)
	$SCRIPTNAME start	
	;;
stop)
	$SCRIPTNAME stop
	;;
restart)
	$SCRIPTNAME restart
	;;
force-reload)
	$SCRIPTNAME force-reload
	;;
status)
	$SCRIPTNAME status
	;;
*) 	
	echo "Usage: $0 <start|stop|restart|force-reload|status>" >&2
	exit 3
	;;
esac
exit 0
